version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - TESTING=0
      - GMAIL_EMAIL=test@test.com
      - GMAIL_APP_PASSWORD=aaaa aaaa aaaa aaaa
      - DATABASE_URL=sqlite:///./finance.db
    working_dir: /app